package v1

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/dnonakolesax/cccad-locks/internal/model"
	locksService "github.com/dnonakolesax/cccad-locks/internal/service/locks"
	"github.com/mailru/easyjson"
)

type LocksService interface {
	Acquire(ctx context.Context, sketchID string, request *model.AcquireLockRequest) (*model.AcquireLockResponse, error)
	Refresh(ctx context.Context, sketchID, lockID string, request *model.RefreshLockRequest) (*model.SketchLock, error)
	Release(ctx context.Context, sketchID, lockID string) error
}

type LocksHandler struct {
	service LocksService
}

func NewLocksHandler(service LocksService) *LocksHandler {
	return &LocksHandler{
		service: service,
	}
}

func (h *LocksHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /{sketchId}/locks", h.Acquire)
	mux.HandleFunc("POST /{sketchId}/locks/{lockId}/refresh", h.Refresh)
	mux.HandleFunc("DELETE /{sketchId}/locks/{lockId}", h.Release)
}

func (h *LocksHandler) Acquire(w http.ResponseWriter, r *http.Request) {
	sketchID := r.PathValue("sketchId")
	if strings.TrimSpace(sketchID) == "" {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", "sketchId is required")
		return
	}

	var request model.AcquireLockRequest
	if err := readJSON(r, &request); err != nil {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", err.Error())
		return
	}
	if len(request.Scope) == 0 {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", "scope is required")
		return
	}
	if !isValidLockMode(request.Mode) {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", "mode must be edit or preview")
		return
	}

	response, err := h.service.Acquire(r.Context(), sketchID, &request)
	if err != nil {
		writeServiceError(w, err)
		return
	}
	if response == nil {
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", "locks service returned nil acquire response")
		return
	}

	writeJSON(w, http.StatusOK, response)
}

func (h *LocksHandler) Refresh(w http.ResponseWriter, r *http.Request) {
	sketchID := r.PathValue("sketchId")
	lockID := r.PathValue("lockId")
	if strings.TrimSpace(sketchID) == "" || strings.TrimSpace(lockID) == "" {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", "sketchId and lockId are required")
		return
	}

	var request model.RefreshLockRequest
	if err := readOptionalJSON(r, &request); err != nil {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", err.Error())
		return
	}

	lock, err := h.service.Refresh(r.Context(), sketchID, lockID, &request)
	if err != nil {
		writeServiceError(w, err)
		return
	}
	if lock == nil {
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", "locks service returned nil lock")
		return
	}

	writeJSON(w, http.StatusOK, lock)
}

func (h *LocksHandler) Release(w http.ResponseWriter, r *http.Request) {
	sketchID := r.PathValue("sketchId")
	lockID := r.PathValue("lockId")
	if strings.TrimSpace(sketchID) == "" || strings.TrimSpace(lockID) == "" {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", "sketchId and lockId are required")
		return
	}

	if err := h.service.Release(r.Context(), sketchID, lockID); err != nil {
		writeServiceError(w, err)
		return
	}

	w.WriteHeader(http.StatusNoContent)
}

func readJSON(r *http.Request, v easyjson.Unmarshaler) error {
	body, err := readBody(r)
	if err != nil {
		return err
	}
	if len(strings.TrimSpace(string(body))) == 0 {
		return errors.New("request body is required")
	}

	return easyjson.Unmarshal(body, v)
}

func readOptionalJSON(r *http.Request, v easyjson.Unmarshaler) error {
	body, err := readBody(r)
	if err != nil {
		return err
	}
	if len(strings.TrimSpace(string(body))) == 0 {
		return nil
	}

	return easyjson.Unmarshal(body, v)
}

func readBody(r *http.Request) ([]byte, error) {
	defer r.Body.Close()

	const maxBodySize = 1 << 20

	body, err := io.ReadAll(io.LimitReader(r.Body, maxBodySize+1))
	if err != nil {
		return nil, err
	}
	if len(body) > maxBodySize {
		return nil, fmt.Errorf("request body exceeds %d bytes", maxBodySize)
	}

	return body, nil
}

func writeJSON(w http.ResponseWriter, status int, v easyjson.Marshaler) {
	body, err := easyjson.Marshal(v)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", err.Error())
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	//nolint:gosec // JSON response is generated by easyjson and written with application/json content type.
	_, _ = w.Write(body)
}

func writeError(w http.ResponseWriter, status int, code, message string) {
	body, err := easyjson.Marshal(&model.ErrorEnvelope{
		Error: model.ErrorObject{
			Code:    code,
			Message: message,
		},
	})
	if err != nil {
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_, _ = w.Write(body)
}

func writeServiceError(w http.ResponseWriter, err error) {
	switch {
	case errors.Is(err, locksService.ErrLockNotFound):
		writeError(w, http.StatusNotFound, "LOCK_NOT_FOUND", err.Error())
	case errors.Is(err, locksService.ErrLockNotOwned):
		writeError(w, http.StatusForbidden, "PERMISSION_DENIED", err.Error())
	default:
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", err.Error())
	}
}

func isValidLockMode(mode string) bool {
	switch mode {
	case "edit", "preview":
		return true
	default:
		return false
	}
}
