package v1

import (
	"errors"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/dnonakolesax/cccad-locks/internal/model"
	"github.com/mailru/easyjson"
)

type SolverService interface {
	Preview(sketchID string, request *model.SolvePreviewRequest) (*model.SolvePreviewResponse, error)
	Analyze(sketchID string) (*model.AnalyzeSketchResponse, error)
}

type SolverHandler struct {
	service SolverService
}

func NewSolverHandler(service SolverService) *SolverHandler {
	return &SolverHandler{
		service: service,
	}
}

func (h *SolverHandler) RegisterRoutes(mux *http.ServeMux) {
	mux.HandleFunc("POST /{sketchId}/solve-preview", h.Preview)
	mux.HandleFunc("POST /{sketchId}/analyze", h.Analyze)
}

func (h *SolverHandler) Preview(w http.ResponseWriter, r *http.Request) {
	sketchID := r.PathValue("sketchId")
	if strings.TrimSpace(sketchID) == "" {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", "sketchId is required")
		return
	}

	var request model.SolvePreviewRequest
	if err := readJSON(r, &request); err != nil {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", err.Error())
		return
	}
	if request.BaseVersion < 0 {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", "baseVersion must be greater than or equal to 0")
		return
	}
	if len(request.Intent) == 0 {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", "intent is required")
		return
	}

	response, err := h.service.Preview(sketchID, &request)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", err.Error())
		return
	}
	if response == nil {
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", "solver service returned nil preview response")
		return
	}

	writeJSON(w, http.StatusOK, response)
}

func (h *SolverHandler) Analyze(w http.ResponseWriter, r *http.Request) {
	sketchID := r.PathValue("sketchId")
	if strings.TrimSpace(sketchID) == "" {
		writeError(w, http.StatusBadRequest, "INVALID_OPERATION", "sketchId is required")
		return
	}

	response, err := h.service.Analyze(sketchID)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", err.Error())
		return
	}
	if response == nil {
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", "solver service returned nil analyze response")
		return
	}

	writeJSON(w, http.StatusOK, response)
}

func readJSON(r *http.Request, v easyjson.Unmarshaler) error {
	defer r.Body.Close()

	const maxBodySize = 1 << 20

	body, err := io.ReadAll(io.LimitReader(r.Body, maxBodySize+1))
	if err != nil {
		return err
	}
	if len(body) > maxBodySize {
		return fmt.Errorf("request body exceeds %d bytes", maxBodySize)
	}
	if len(strings.TrimSpace(string(body))) == 0 {
		return errors.New("request body is required")
	}

	return easyjson.Unmarshal(body, v)
}

func writeJSON(w http.ResponseWriter, status int, v easyjson.Marshaler) {
	body, err := easyjson.Marshal(v)
	if err != nil {
		writeError(w, http.StatusInternalServerError, "INTERNAL_ERROR", err.Error())
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	//nolint:gosec // JSON response is generated by easyjson and written with application/json content type.
	_, _ = w.Write(body)
}

func writeError(w http.ResponseWriter, status int, code, message string) {
	body, err := easyjson.Marshal(&model.ErrorEnvelope{
		Error: model.ErrorObject{
			Code:    code,
			Message: message,
		},
	})
	if err != nil {
		http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(status)
	_, _ = w.Write(body)
}
