// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel(in *jlexer.Lexer, out *UpdateCommentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "body":
			if in.IsNull() {
				in.Skip()
				out.Body = nil
			} else {
				if out.Body == nil {
					out.Body = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Body = string(in.String())
				}
			}
		case "anchor":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Anchor).UnmarshalEasyJSON(in)
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Metadata).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel(out *jwriter.Writer, in UpdateCommentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Body != nil {
		const prefix string = ",\"body\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Body))
	}
	if (in.Anchor).IsDefined() {
		const prefix string = ",\"anchor\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Anchor).MarshalEasyJSON(out)
	}
	if (in.Metadata).IsDefined() {
		const prefix string = ",\"metadata\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		(in.Metadata).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateCommentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateCommentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateCommentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateCommentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel1(in *jlexer.Lexer, out *ReplaceCommentAssigneesRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "assigneeUserIds":
			if in.IsNull() {
				in.Skip()
				out.AssigneeUserIDs = nil
			} else {
				in.Delim('[')
				if out.AssigneeUserIDs == nil {
					if !in.IsDelim(']') {
						out.AssigneeUserIDs = make([]string, 0, 4)
					} else {
						out.AssigneeUserIDs = []string{}
					}
				} else {
					out.AssigneeUserIDs = (out.AssigneeUserIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.AssigneeUserIDs = append(out.AssigneeUserIDs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel1(out *jwriter.Writer, in ReplaceCommentAssigneesRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"assigneeUserIds\":"
		out.RawString(prefix[1:])
		if in.AssigneeUserIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.AssigneeUserIDs {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ReplaceCommentAssigneesRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ReplaceCommentAssigneesRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ReplaceCommentAssigneesRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ReplaceCommentAssigneesRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel1(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel2(in *jlexer.Lexer, out *CreateCommentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "parentCommentId":
			if in.IsNull() {
				in.Skip()
				out.ParentCommentID = nil
			} else {
				if out.ParentCommentID == nil {
					out.ParentCommentID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ParentCommentID = string(in.String())
				}
			}
		case "sketchId":
			if in.IsNull() {
				in.Skip()
				out.SketchID = nil
			} else {
				if out.SketchID == nil {
					out.SketchID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.SketchID = string(in.String())
				}
			}
		case "partId":
			if in.IsNull() {
				in.Skip()
				out.PartID = nil
			} else {
				if out.PartID == nil {
					out.PartID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PartID = string(in.String())
				}
			}
		case "targetType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TargetType = string(in.String())
			}
		case "targetId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TargetID = string(in.String())
			}
		case "kind":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = string(in.String())
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "assigneeUserIds":
			if in.IsNull() {
				in.Skip()
				out.AssigneeUserIDs = nil
			} else {
				in.Delim('[')
				if out.AssigneeUserIDs == nil {
					if !in.IsDelim(']') {
						out.AssigneeUserIDs = make([]string, 0, 4)
					} else {
						out.AssigneeUserIDs = []string{}
					}
				} else {
					out.AssigneeUserIDs = (out.AssigneeUserIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v4 string
					if in.IsNull() {
						in.Skip()
					} else {
						v4 = string(in.String())
					}
					out.AssigneeUserIDs = append(out.AssigneeUserIDs, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "sketchVersion":
			if in.IsNull() {
				in.Skip()
				out.SketchVersion = nil
			} else {
				if out.SketchVersion == nil {
					out.SketchVersion = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.SketchVersion = int64(in.Int64())
				}
			}
		case "partVersion":
			if in.IsNull() {
				in.Skip()
				out.PartVersion = nil
			} else {
				if out.PartVersion == nil {
					out.PartVersion = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PartVersion = int64(in.Int64())
				}
			}
		case "anchor":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Anchor).UnmarshalEasyJSON(in)
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Metadata).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel2(out *jwriter.Writer, in CreateCommentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ParentCommentID != nil {
		const prefix string = ",\"parentCommentId\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.ParentCommentID))
	}
	if in.SketchID != nil {
		const prefix string = ",\"sketchId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.SketchID))
	}
	if in.PartID != nil {
		const prefix string = ",\"partId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.PartID))
	}
	if in.TargetType != "" {
		const prefix string = ",\"targetType\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.TargetType))
	}
	if in.TargetID != "" {
		const prefix string = ",\"targetId\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.TargetID))
	}
	if in.Kind != "" {
		const prefix string = ",\"kind\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Kind))
	}
	{
		const prefix string = ",\"body\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Body))
	}
	if len(in.AssigneeUserIDs) != 0 {
		const prefix string = ",\"assigneeUserIds\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v5, v6 := range in.AssigneeUserIDs {
				if v5 > 0 {
					out.RawByte(',')
				}
				out.String(string(v6))
			}
			out.RawByte(']')
		}
	}
	if in.Status != "" {
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	if in.SketchVersion != nil {
		const prefix string = ",\"sketchVersion\":"
		out.RawString(prefix)
		out.Int64(int64(*in.SketchVersion))
	}
	if in.PartVersion != nil {
		const prefix string = ",\"partVersion\":"
		out.RawString(prefix)
		out.Int64(int64(*in.PartVersion))
	}
	if (in.Anchor).IsDefined() {
		const prefix string = ",\"anchor\":"
		out.RawString(prefix)
		(in.Anchor).MarshalEasyJSON(out)
	}
	if (in.Metadata).IsDefined() {
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		(in.Metadata).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateCommentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateCommentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateCommentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateCommentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel2(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel3(in *jlexer.Lexer, out *CreateCommentReplyRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "assigneeUserIds":
			if in.IsNull() {
				in.Skip()
				out.AssigneeUserIDs = nil
			} else {
				in.Delim('[')
				if out.AssigneeUserIDs == nil {
					if !in.IsDelim(']') {
						out.AssigneeUserIDs = make([]string, 0, 4)
					} else {
						out.AssigneeUserIDs = []string{}
					}
				} else {
					out.AssigneeUserIDs = (out.AssigneeUserIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					if in.IsNull() {
						in.Skip()
					} else {
						v7 = string(in.String())
					}
					out.AssigneeUserIDs = append(out.AssigneeUserIDs, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "anchor":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Anchor).UnmarshalEasyJSON(in)
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Metadata).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel3(out *jwriter.Writer, in CreateCommentReplyRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix[1:])
		out.String(string(in.Body))
	}
	if len(in.AssigneeUserIDs) != 0 {
		const prefix string = ",\"assigneeUserIds\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.AssigneeUserIDs {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	if (in.Anchor).IsDefined() {
		const prefix string = ",\"anchor\":"
		out.RawString(prefix)
		(in.Anchor).MarshalEasyJSON(out)
	}
	if (in.Metadata).IsDefined() {
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		(in.Metadata).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateCommentReplyRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateCommentReplyRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateCommentReplyRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateCommentReplyRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel3(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel4(in *jlexer.Lexer, out *CommentThreadResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "root":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Root).UnmarshalEasyJSON(in)
			}
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]CadComment, 0, 0)
					} else {
						out.Items = []CadComment{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v10 CadComment
					if in.IsNull() {
						in.Skip()
					} else {
						(v10).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel4(out *jwriter.Writer, in CommentThreadResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"root\":"
		out.RawString(prefix[1:])
		(in.Root).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix)
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Items {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentThreadResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentThreadResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentThreadResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentThreadResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel4(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel5(in *jlexer.Lexer, out *CommentStatusHistoryResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]CommentStatusHistoryItem, 0, 0)
					} else {
						out.Items = []CommentStatusHistoryItem{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v13 CommentStatusHistoryItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v13).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v13)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel5(out *jwriter.Writer, in CommentStatusHistoryResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Items {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentStatusHistoryResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentStatusHistoryResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentStatusHistoryResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentStatusHistoryResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel5(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel6(in *jlexer.Lexer, out *CommentStatusHistoryItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "commentId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CommentID = string(in.String())
			}
		case "oldStatus":
			if in.IsNull() {
				in.Skip()
				out.OldStatus = nil
			} else {
				if out.OldStatus == nil {
					out.OldStatus = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.OldStatus = string(in.String())
				}
			}
		case "newStatus":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NewStatus = string(in.String())
			}
		case "changedByUserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChangedByUserID = string(in.String())
			}
		case "changedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ChangedAt = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
				out.Reason = nil
			} else {
				if out.Reason == nil {
					out.Reason = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Reason = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel6(out *jwriter.Writer, in CommentStatusHistoryItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"commentId\":"
		out.RawString(prefix)
		out.String(string(in.CommentID))
	}
	if in.OldStatus != nil {
		const prefix string = ",\"oldStatus\":"
		out.RawString(prefix)
		out.String(string(*in.OldStatus))
	}
	{
		const prefix string = ",\"newStatus\":"
		out.RawString(prefix)
		out.String(string(in.NewStatus))
	}
	{
		const prefix string = ",\"changedByUserId\":"
		out.RawString(prefix)
		out.String(string(in.ChangedByUserID))
	}
	{
		const prefix string = ",\"changedAt\":"
		out.RawString(prefix)
		out.String(string(in.ChangedAt))
	}
	if in.Reason != nil {
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(*in.Reason))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentStatusHistoryItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentStatusHistoryItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentStatusHistoryItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentStatusHistoryItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel6(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel7(in *jlexer.Lexer, out *CommentRealtimeEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "eventId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EventID = string(in.String())
			}
		case "workspaceId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WorkspaceID = string(in.String())
			}
		case "occurredAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OccurredAt = string(in.String())
			}
		case "actorUserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ActorUserID = string(in.String())
			}
		case "payload":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Payload).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel7(out *jwriter.Writer, in CommentRealtimeEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"eventId\":"
		out.RawString(prefix)
		out.String(string(in.EventID))
	}
	{
		const prefix string = ",\"workspaceId\":"
		out.RawString(prefix)
		out.String(string(in.WorkspaceID))
	}
	{
		const prefix string = ",\"occurredAt\":"
		out.RawString(prefix)
		out.String(string(in.OccurredAt))
	}
	{
		const prefix string = ",\"actorUserId\":"
		out.RawString(prefix)
		out.String(string(in.ActorUserID))
	}
	{
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		(in.Payload).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentRealtimeEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentRealtimeEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentRealtimeEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentRealtimeEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel7(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel8(in *jlexer.Lexer, out *CommentListResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]CadComment, 0, 0)
					} else {
						out.Items = []CadComment{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v16 CadComment
					if in.IsNull() {
						in.Skip()
					} else {
						(v16).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		case "total":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Total = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel8(out *jwriter.Writer, in CommentListResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v17, v18 := range in.Items {
				if v17 > 0 {
					out.RawByte(',')
				}
				(v18).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	{
		const prefix string = ",\"total\":"
		out.RawString(prefix)
		out.Int(int(in.Total))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentListResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentListResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentListResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentListResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel8(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel9(in *jlexer.Lexer, out *CommentListFilter) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "WorkspaceID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WorkspaceID = string(in.String())
			}
		case "SketchID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SketchID = string(in.String())
			}
		case "PartID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.PartID = string(in.String())
			}
		case "TargetType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TargetType = string(in.String())
			}
		case "TargetID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TargetID = string(in.String())
			}
		case "Kind":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = string(in.String())
			}
		case "Status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "MessageType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessageType = string(in.String())
			}
		case "SystemEventType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SystemEventType = string(in.String())
			}
		case "AssigneeUserID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AssigneeUserID = string(in.String())
			}
		case "ParentCommentID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ParentCommentID = string(in.String())
			}
		case "ThreadRootID":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ThreadRootID = string(in.String())
			}
		case "RootsOnly":
			if in.IsNull() {
				in.Skip()
			} else {
				out.RootsOnly = bool(in.Bool())
			}
		case "IncludeDeleted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IncludeDeleted = bool(in.Bool())
			}
		case "IncludeSystem":
			if in.IsNull() {
				in.Skip()
			} else {
				out.IncludeSystem = bool(in.Bool())
			}
		case "MaxDepth":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MaxDepth = int(in.Int())
			}
		case "Limit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Limit = int(in.Int())
			}
		case "Offset":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Offset = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel9(out *jwriter.Writer, in CommentListFilter) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"WorkspaceID\":"
		out.RawString(prefix[1:])
		out.String(string(in.WorkspaceID))
	}
	{
		const prefix string = ",\"SketchID\":"
		out.RawString(prefix)
		out.String(string(in.SketchID))
	}
	{
		const prefix string = ",\"PartID\":"
		out.RawString(prefix)
		out.String(string(in.PartID))
	}
	{
		const prefix string = ",\"TargetType\":"
		out.RawString(prefix)
		out.String(string(in.TargetType))
	}
	{
		const prefix string = ",\"TargetID\":"
		out.RawString(prefix)
		out.String(string(in.TargetID))
	}
	{
		const prefix string = ",\"Kind\":"
		out.RawString(prefix)
		out.String(string(in.Kind))
	}
	{
		const prefix string = ",\"Status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"MessageType\":"
		out.RawString(prefix)
		out.String(string(in.MessageType))
	}
	{
		const prefix string = ",\"SystemEventType\":"
		out.RawString(prefix)
		out.String(string(in.SystemEventType))
	}
	{
		const prefix string = ",\"AssigneeUserID\":"
		out.RawString(prefix)
		out.String(string(in.AssigneeUserID))
	}
	{
		const prefix string = ",\"ParentCommentID\":"
		out.RawString(prefix)
		out.String(string(in.ParentCommentID))
	}
	{
		const prefix string = ",\"ThreadRootID\":"
		out.RawString(prefix)
		out.String(string(in.ThreadRootID))
	}
	{
		const prefix string = ",\"RootsOnly\":"
		out.RawString(prefix)
		out.Bool(bool(in.RootsOnly))
	}
	{
		const prefix string = ",\"IncludeDeleted\":"
		out.RawString(prefix)
		out.Bool(bool(in.IncludeDeleted))
	}
	{
		const prefix string = ",\"IncludeSystem\":"
		out.RawString(prefix)
		out.Bool(bool(in.IncludeSystem))
	}
	{
		const prefix string = ",\"MaxDepth\":"
		out.RawString(prefix)
		out.Int(int(in.MaxDepth))
	}
	{
		const prefix string = ",\"Limit\":"
		out.RawString(prefix)
		out.Int(int(in.Limit))
	}
	{
		const prefix string = ",\"Offset\":"
		out.RawString(prefix)
		out.Int(int(in.Offset))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentListFilter) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentListFilter) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentListFilter) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentListFilter) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel9(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel10(in *jlexer.Lexer, out *CommentEditHistoryResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "items":
			if in.IsNull() {
				in.Skip()
				out.Items = nil
			} else {
				in.Delim('[')
				if out.Items == nil {
					if !in.IsDelim(']') {
						out.Items = make([]CommentEditHistoryItem, 0, 0)
					} else {
						out.Items = []CommentEditHistoryItem{}
					}
				} else {
					out.Items = (out.Items)[:0]
				}
				for !in.IsDelim(']') {
					var v19 CommentEditHistoryItem
					if in.IsNull() {
						in.Skip()
					} else {
						(v19).UnmarshalEasyJSON(in)
					}
					out.Items = append(out.Items, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel10(out *jwriter.Writer, in CommentEditHistoryResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"items\":"
		out.RawString(prefix[1:])
		if in.Items == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Items {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentEditHistoryResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentEditHistoryResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentEditHistoryResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentEditHistoryResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel10(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel11(in *jlexer.Lexer, out *CommentEditHistoryItem) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "commentId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CommentID = string(in.String())
			}
		case "oldBody":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OldBody = string(in.String())
			}
		case "newBody":
			if in.IsNull() {
				in.Skip()
			} else {
				out.NewBody = string(in.String())
			}
		case "editedByUserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EditedByUserID = string(in.String())
			}
		case "editedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.EditedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel11(out *jwriter.Writer, in CommentEditHistoryItem) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"commentId\":"
		out.RawString(prefix)
		out.String(string(in.CommentID))
	}
	{
		const prefix string = ",\"oldBody\":"
		out.RawString(prefix)
		out.String(string(in.OldBody))
	}
	{
		const prefix string = ",\"newBody\":"
		out.RawString(prefix)
		out.String(string(in.NewBody))
	}
	{
		const prefix string = ",\"editedByUserId\":"
		out.RawString(prefix)
		out.String(string(in.EditedByUserID))
	}
	{
		const prefix string = ",\"editedAt\":"
		out.RawString(prefix)
		out.String(string(in.EditedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CommentEditHistoryItem) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CommentEditHistoryItem) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CommentEditHistoryItem) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CommentEditHistoryItem) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel11(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel12(in *jlexer.Lexer, out *ChangeCommentStatusResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "comment":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Comment).UnmarshalEasyJSON(in)
			}
		case "systemMessage":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.SystemMessage).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel12(out *jwriter.Writer, in ChangeCommentStatusResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"comment\":"
		out.RawString(prefix[1:])
		(in.Comment).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"systemMessage\":"
		out.RawString(prefix)
		(in.SystemMessage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChangeCommentStatusResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChangeCommentStatusResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChangeCommentStatusResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChangeCommentStatusResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel12(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel13(in *jlexer.Lexer, out *ChangeCommentStatusRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "reason":
			if in.IsNull() {
				in.Skip()
				out.Reason = nil
			} else {
				if out.Reason == nil {
					out.Reason = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Reason = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel13(out *jwriter.Writer, in ChangeCommentStatusRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	if in.Reason != nil {
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(*in.Reason))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChangeCommentStatusRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChangeCommentStatusRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChangeCommentStatusRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChangeCommentStatusRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel13(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel14(in *jlexer.Lexer, out *ChangeCommentAssigneesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "comment":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Comment).UnmarshalEasyJSON(in)
			}
		case "systemMessage":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.SystemMessage).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel14(out *jwriter.Writer, in ChangeCommentAssigneesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"comment\":"
		out.RawString(prefix[1:])
		(in.Comment).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"systemMessage\":"
		out.RawString(prefix)
		(in.SystemMessage).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ChangeCommentAssigneesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ChangeCommentAssigneesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ChangeCommentAssigneesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ChangeCommentAssigneesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel14(l, v)
}
func easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel15(in *jlexer.Lexer, out *CadComment) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "workspaceId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WorkspaceID = string(in.String())
			}
		case "sketchId":
			if in.IsNull() {
				in.Skip()
				out.SketchID = nil
			} else {
				if out.SketchID == nil {
					out.SketchID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.SketchID = string(in.String())
				}
			}
		case "partId":
			if in.IsNull() {
				in.Skip()
				out.PartID = nil
			} else {
				if out.PartID == nil {
					out.PartID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PartID = string(in.String())
				}
			}
		case "parentCommentId":
			if in.IsNull() {
				in.Skip()
				out.ParentCommentID = nil
			} else {
				if out.ParentCommentID == nil {
					out.ParentCommentID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.ParentCommentID = string(in.String())
				}
			}
		case "threadRootId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ThreadRootID = string(in.String())
			}
		case "replyDepth":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReplyDepth = int(in.Int())
			}
		case "replyCount":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ReplyCount = int(in.Int())
			}
		case "messageType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.MessageType = string(in.String())
			}
		case "systemEventType":
			if in.IsNull() {
				in.Skip()
				out.SystemEventType = nil
			} else {
				if out.SystemEventType == nil {
					out.SystemEventType = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.SystemEventType = string(in.String())
				}
			}
		case "eventPayload":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.EventPayload).UnmarshalEasyJSON(in)
			}
		case "targetType":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TargetType = string(in.String())
			}
		case "targetId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TargetID = string(in.String())
			}
		case "kind":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Kind = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "authorUserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.AuthorUserID = string(in.String())
			}
		case "assigneeUserIds":
			if in.IsNull() {
				in.Skip()
				out.AssigneeUserIDs = nil
			} else {
				in.Delim('[')
				if out.AssigneeUserIDs == nil {
					if !in.IsDelim(']') {
						out.AssigneeUserIDs = make([]string, 0, 4)
					} else {
						out.AssigneeUserIDs = []string{}
					}
				} else {
					out.AssigneeUserIDs = (out.AssigneeUserIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					out.AssigneeUserIDs = append(out.AssigneeUserIDs, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "body":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Body = string(in.String())
			}
		case "sketchVersion":
			if in.IsNull() {
				in.Skip()
				out.SketchVersion = nil
			} else {
				if out.SketchVersion == nil {
					out.SketchVersion = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.SketchVersion = int64(in.Int64())
				}
			}
		case "partVersion":
			if in.IsNull() {
				in.Skip()
				out.PartVersion = nil
			} else {
				if out.PartVersion == nil {
					out.PartVersion = new(int64)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.PartVersion = int64(in.Int64())
				}
			}
		case "anchor":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Anchor).UnmarshalEasyJSON(in)
			}
		case "metadata":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Metadata).UnmarshalEasyJSON(in)
			}
		case "createdAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "updatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdatedAt = string(in.String())
			}
		case "deletedAt":
			if in.IsNull() {
				in.Skip()
				out.DeletedAt = nil
			} else {
				if out.DeletedAt == nil {
					out.DeletedAt = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.DeletedAt = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel15(out *jwriter.Writer, in CadComment) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"workspaceId\":"
		out.RawString(prefix)
		out.String(string(in.WorkspaceID))
	}
	if in.SketchID != nil {
		const prefix string = ",\"sketchId\":"
		out.RawString(prefix)
		out.String(string(*in.SketchID))
	}
	if in.PartID != nil {
		const prefix string = ",\"partId\":"
		out.RawString(prefix)
		out.String(string(*in.PartID))
	}
	if in.ParentCommentID != nil {
		const prefix string = ",\"parentCommentId\":"
		out.RawString(prefix)
		out.String(string(*in.ParentCommentID))
	}
	{
		const prefix string = ",\"threadRootId\":"
		out.RawString(prefix)
		out.String(string(in.ThreadRootID))
	}
	{
		const prefix string = ",\"replyDepth\":"
		out.RawString(prefix)
		out.Int(int(in.ReplyDepth))
	}
	if in.ReplyCount != 0 {
		const prefix string = ",\"replyCount\":"
		out.RawString(prefix)
		out.Int(int(in.ReplyCount))
	}
	{
		const prefix string = ",\"messageType\":"
		out.RawString(prefix)
		out.String(string(in.MessageType))
	}
	if in.SystemEventType != nil {
		const prefix string = ",\"systemEventType\":"
		out.RawString(prefix)
		out.String(string(*in.SystemEventType))
	}
	{
		const prefix string = ",\"eventPayload\":"
		out.RawString(prefix)
		(in.EventPayload).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"targetType\":"
		out.RawString(prefix)
		out.String(string(in.TargetType))
	}
	{
		const prefix string = ",\"targetId\":"
		out.RawString(prefix)
		out.String(string(in.TargetID))
	}
	{
		const prefix string = ",\"kind\":"
		out.RawString(prefix)
		out.String(string(in.Kind))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"authorUserId\":"
		out.RawString(prefix)
		out.String(string(in.AuthorUserID))
	}
	{
		const prefix string = ",\"assigneeUserIds\":"
		out.RawString(prefix)
		if in.AssigneeUserIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v23, v24 := range in.AssigneeUserIDs {
				if v23 > 0 {
					out.RawByte(',')
				}
				out.String(string(v24))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"body\":"
		out.RawString(prefix)
		out.String(string(in.Body))
	}
	if in.SketchVersion != nil {
		const prefix string = ",\"sketchVersion\":"
		out.RawString(prefix)
		out.Int64(int64(*in.SketchVersion))
	}
	if in.PartVersion != nil {
		const prefix string = ",\"partVersion\":"
		out.RawString(prefix)
		out.Int64(int64(*in.PartVersion))
	}
	if (in.Anchor).IsDefined() {
		const prefix string = ",\"anchor\":"
		out.RawString(prefix)
		(in.Anchor).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"metadata\":"
		out.RawString(prefix)
		(in.Metadata).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	if in.DeletedAt != nil {
		const prefix string = ",\"deletedAt\":"
		out.RawString(prefix)
		out.String(string(*in.DeletedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CadComment) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CadComment) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE9abebc9EncodeGithubComDnonakolesaxCccadLocksInternalModel15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CadComment) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CadComment) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE9abebc9DecodeGithubComDnonakolesaxCccadLocksInternalModel15(l, v)
}
