// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel(in *jlexer.Lexer, out *SketchLock) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "sketchId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SketchID = string(in.String())
			}
		case "ownerUserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.OwnerUserID = string(in.String())
			}
		case "scope":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Scope).UnmarshalEasyJSON(in)
			}
		case "mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Mode = string(in.String())
			}
		case "expiresAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ExpiresAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel(out *jwriter.Writer, in SketchLock) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"sketchId\":"
		out.RawString(prefix)
		out.String(string(in.SketchID))
	}
	{
		const prefix string = ",\"ownerUserId\":"
		out.RawString(prefix)
		out.String(string(in.OwnerUserID))
	}
	{
		const prefix string = ",\"scope\":"
		out.RawString(prefix)
		(in.Scope).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"mode\":"
		out.RawString(prefix)
		out.String(string(in.Mode))
	}
	{
		const prefix string = ",\"expiresAt\":"
		out.RawString(prefix)
		out.String(string(in.ExpiresAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SketchLock) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SketchLock) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SketchLock) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SketchLock) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel(l, v)
}
func easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel1(in *jlexer.Lexer, out *RefreshLockRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "ttlMs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TTLMS = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel1(out *jwriter.Writer, in RefreshLockRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.TTLMS != 0 {
		const prefix string = ",\"ttlMs\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.TTLMS))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RefreshLockRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RefreshLockRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RefreshLockRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RefreshLockRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel1(l, v)
}
func easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel2(in *jlexer.Lexer, out *LockConflict) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "holderUserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.HolderUserID = string(in.String())
			}
		case "lockId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.LockID = string(in.String())
			}
		case "scope":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Scope).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel2(out *jwriter.Writer, in LockConflict) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"holderUserId\":"
		out.RawString(prefix[1:])
		out.String(string(in.HolderUserID))
	}
	{
		const prefix string = ",\"lockId\":"
		out.RawString(prefix)
		out.String(string(in.LockID))
	}
	{
		const prefix string = ",\"scope\":"
		out.RawString(prefix)
		(in.Scope).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LockConflict) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LockConflict) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LockConflict) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LockConflict) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel2(l, v)
}
func easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel3(in *jlexer.Lexer, out *AcquireLockResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "granted":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Granted = bool(in.Bool())
			}
		case "lock":
			if in.IsNull() {
				in.Skip()
				out.Lock = nil
			} else {
				if out.Lock == nil {
					out.Lock = new(SketchLock)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Lock).UnmarshalEasyJSON(in)
				}
			}
		case "conflict":
			if in.IsNull() {
				in.Skip()
				out.Conflict = nil
			} else {
				if out.Conflict == nil {
					out.Conflict = new(LockConflict)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Conflict).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel3(out *jwriter.Writer, in AcquireLockResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"granted\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Granted))
	}
	if in.Lock != nil {
		const prefix string = ",\"lock\":"
		out.RawString(prefix)
		(*in.Lock).MarshalEasyJSON(out)
	}
	if in.Conflict != nil {
		const prefix string = ",\"conflict\":"
		out.RawString(prefix)
		(*in.Conflict).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AcquireLockResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AcquireLockResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AcquireLockResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AcquireLockResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel3(l, v)
}
func easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel4(in *jlexer.Lexer, out *AcquireLockRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "scope":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Scope).UnmarshalEasyJSON(in)
			}
		case "mode":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Mode = string(in.String())
			}
		case "ttlMs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.TTLMS = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel4(out *jwriter.Writer, in AcquireLockRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"scope\":"
		out.RawString(prefix[1:])
		(in.Scope).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"mode\":"
		out.RawString(prefix)
		out.String(string(in.Mode))
	}
	if in.TTLMS != 0 {
		const prefix string = ",\"ttlMs\":"
		out.RawString(prefix)
		out.Int(int(in.TTLMS))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AcquireLockRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AcquireLockRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonAe542dd9EncodeGithubComDnonakolesaxCccadLocksInternalModel4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AcquireLockRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AcquireLockRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonAe542dd9DecodeGithubComDnonakolesaxCccadLocksInternalModel4(l, v)
}
