// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel(in *jlexer.Lexer, out *SetPermissionRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel(out *jwriter.Writer, in SetPermissionRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix[1:])
		out.String(string(in.Role))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SetPermissionRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SetPermissionRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SetPermissionRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SetPermissionRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel(l, v)
}
func easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel1(in *jlexer.Lexer, out *PermissionList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sketchId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SketchID = string(in.String())
			}
		case "permissions":
			if in.IsNull() {
				in.Skip()
				out.Permissions = nil
			} else {
				in.Delim('[')
				if out.Permissions == nil {
					if !in.IsDelim(']') {
						out.Permissions = make([]Permission, 0, 0)
					} else {
						out.Permissions = []Permission{}
					}
				} else {
					out.Permissions = (out.Permissions)[:0]
				}
				for !in.IsDelim(']') {
					var v1 Permission
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					out.Permissions = append(out.Permissions, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel1(out *jwriter.Writer, in PermissionList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sketchId\":"
		out.RawString(prefix[1:])
		out.String(string(in.SketchID))
	}
	{
		const prefix string = ",\"permissions\":"
		out.RawString(prefix)
		if in.Permissions == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Permissions {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PermissionList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PermissionList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PermissionList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PermissionList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel1(l, v)
}
func easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel2(in *jlexer.Lexer, out *Permission) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sketchId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.SketchID = string(in.String())
			}
		case "userId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UserID = string(in.String())
			}
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = string(in.String())
			}
		case "source":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Source = string(in.String())
			}
		case "grantedByUserId":
			if in.IsNull() {
				in.Skip()
				out.GrantedByUserID = nil
			} else {
				if out.GrantedByUserID == nil {
					out.GrantedByUserID = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.GrantedByUserID = string(in.String())
				}
			}
		case "createdAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "updatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdatedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel2(out *jwriter.Writer, in Permission) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sketchId\":"
		out.RawString(prefix[1:])
		out.String(string(in.SketchID))
	}
	{
		const prefix string = ",\"userId\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"source\":"
		out.RawString(prefix)
		out.String(string(in.Source))
	}
	{
		const prefix string = ",\"grantedByUserId\":"
		out.RawString(prefix)
		if in.GrantedByUserID == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.GrantedByUserID))
		}
	}
	{
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Permission) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Permission) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Permission) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Permission) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel2(l, v)
}
func easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel3(in *jlexer.Lexer, out *ErrorObject) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "details":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				if !in.IsDelim('}') {
					out.Details = make(map[string]interface{})
				} else {
					out.Details = nil
				}
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v4 interface{}
					if m, ok := v4.(easyjson.Unmarshaler); ok {
						m.UnmarshalEasyJSON(in)
					} else if m, ok := v4.(json.Unmarshaler); ok {
						_ = m.UnmarshalJSON(in.Raw())
					} else {
						v4 = in.Interface()
					}
					(out.Details)[key] = v4
					in.WantComma()
				}
				in.Delim('}')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel3(out *jwriter.Writer, in ErrorObject) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix[1:])
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	if len(in.Details) != 0 {
		const prefix string = ",\"details\":"
		out.RawString(prefix)
		{
			out.RawByte('{')
			v5First := true
			for v5Name, v5Value := range in.Details {
				if v5First {
					v5First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v5Name))
				out.RawByte(':')
				if m, ok := v5Value.(easyjson.Marshaler); ok {
					m.MarshalEasyJSON(out)
				} else if m, ok := v5Value.(json.Marshaler); ok {
					out.Raw(m.MarshalJSON())
				} else {
					out.Raw(json.Marshal(v5Value))
				}
			}
			out.RawByte('}')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorObject) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorObject) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorObject) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorObject) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel3(l, v)
}
func easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel4(in *jlexer.Lexer, out *ErrorEnvelope) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "error":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Error).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel4(out *jwriter.Writer, in ErrorEnvelope) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		(in.Error).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorEnvelope) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorEnvelope) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF9c5ab41EncodeGithubComDnonakolesaxCccadLocksInternalModel4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorEnvelope) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorEnvelope) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF9c5ab41DecodeGithubComDnonakolesaxCccadLocksInternalModel4(l, v)
}
