// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel(in *jlexer.Lexer, out *Vector3) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "x":
			if in.IsNull() {
				in.Skip()
			} else {
				out.X = float64(in.Float64())
			}
		case "y":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Y = float64(in.Float64())
			}
		case "z":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Z = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel(out *jwriter.Writer, in Vector3) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"x\":"
		out.RawString(prefix[1:])
		out.Float64(float64(in.X))
	}
	{
		const prefix string = ",\"y\":"
		out.RawString(prefix)
		out.Float64(float64(in.Y))
	}
	{
		const prefix string = ",\"z\":"
		out.RawString(prefix)
		out.Float64(float64(in.Z))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Vector3) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Vector3) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Vector3) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Vector3) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel(l, v)
}
func easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel1(in *jlexer.Lexer, out *UpdateSketchMetadataRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Name = string(in.String())
				}
			}
		case "unit":
			if in.IsNull() {
				in.Skip()
				out.Unit = nil
			} else {
				if out.Unit == nil {
					out.Unit = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Unit = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel1(out *jwriter.Writer, in UpdateSketchMetadataRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Name != nil {
		const prefix string = ",\"name\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(*in.Name))
	}
	if in.Unit != nil {
		const prefix string = ",\"unit\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(*in.Unit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateSketchMetadataRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateSketchMetadataRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateSketchMetadataRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateSketchMetadataRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel1(l, v)
}
func easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel2(in *jlexer.Lexer, out *SketchPlane) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "origin":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Origin).UnmarshalEasyJSON(in)
			}
		case "normal":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Normal).UnmarshalEasyJSON(in)
			}
		case "xAxis":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.XAxis).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel2(out *jwriter.Writer, in SketchPlane) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"origin\":"
		out.RawString(prefix[1:])
		(in.Origin).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"normal\":"
		out.RawString(prefix)
		(in.Normal).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"xAxis\":"
		out.RawString(prefix)
		(in.XAxis).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SketchPlane) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SketchPlane) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SketchPlane) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SketchPlane) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel2(l, v)
}
func easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel3(in *jlexer.Lexer, out *SketchMetadata) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "workspaceId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WorkspaceID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "createdByUserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedByUserID = string(in.String())
			}
		case "unit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Unit = string(in.String())
			}
		case "plane":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Plane).UnmarshalEasyJSON(in)
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = int64(in.Int64())
			}
		case "createdAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "updatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdatedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel3(out *jwriter.Writer, in SketchMetadata) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"workspaceId\":"
		out.RawString(prefix)
		out.String(string(in.WorkspaceID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"createdByUserId\":"
		out.RawString(prefix)
		out.String(string(in.CreatedByUserID))
	}
	{
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	{
		const prefix string = ",\"plane\":"
		out.RawString(prefix)
		(in.Plane).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.Int64(int64(in.Version))
	}
	{
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SketchMetadata) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SketchMetadata) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SketchMetadata) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SketchMetadata) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel3(l, v)
}
func easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel4(in *jlexer.Lexer, out *SketchDocument) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "workspaceId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WorkspaceID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "createdByUserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedByUserID = string(in.String())
			}
		case "unit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Unit = string(in.String())
			}
		case "plane":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Plane).UnmarshalEasyJSON(in)
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = int64(in.Int64())
			}
		case "entities":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Entities = make(map[string]easyjson.RawMessage)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v1 easyjson.RawMessage
					if in.IsNull() {
						in.Skip()
					} else {
						(v1).UnmarshalEasyJSON(in)
					}
					(out.Entities)[key] = v1
					in.WantComma()
				}
				in.Delim('}')
			}
		case "constraints":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Constraints = make(map[string]easyjson.RawMessage)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v2 easyjson.RawMessage
					if in.IsNull() {
						in.Skip()
					} else {
						(v2).UnmarshalEasyJSON(in)
					}
					(out.Constraints)[key] = v2
					in.WantComma()
				}
				in.Delim('}')
			}
		case "dimensions":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Dimensions = make(map[string]easyjson.RawMessage)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v3 easyjson.RawMessage
					if in.IsNull() {
						in.Skip()
					} else {
						(v3).UnmarshalEasyJSON(in)
					}
					(out.Dimensions)[key] = v3
					in.WantComma()
				}
				in.Delim('}')
			}
		case "groups":
			if in.IsNull() {
				in.Skip()
			} else {
				in.Delim('{')
				out.Groups = make(map[string]easyjson.RawMessage)
				for !in.IsDelim('}') {
					key := string(in.String())
					in.WantColon()
					var v4 easyjson.RawMessage
					if in.IsNull() {
						in.Skip()
					} else {
						(v4).UnmarshalEasyJSON(in)
					}
					(out.Groups)[key] = v4
					in.WantComma()
				}
				in.Delim('}')
			}
		case "solveStatus":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.SolveStatus).UnmarshalEasyJSON(in)
			}
		case "profiles":
			if in.IsNull() {
				in.Skip()
				out.Profiles = nil
			} else {
				in.Delim('[')
				if out.Profiles == nil {
					if !in.IsDelim(']') {
						out.Profiles = make([]easyjson.RawMessage, 0, 2)
					} else {
						out.Profiles = []easyjson.RawMessage{}
					}
				} else {
					out.Profiles = (out.Profiles)[:0]
				}
				for !in.IsDelim(']') {
					var v5 easyjson.RawMessage
					if in.IsNull() {
						in.Skip()
					} else {
						(v5).UnmarshalEasyJSON(in)
					}
					out.Profiles = append(out.Profiles, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "conflicts":
			if in.IsNull() {
				in.Skip()
				out.Conflicts = nil
			} else {
				in.Delim('[')
				if out.Conflicts == nil {
					if !in.IsDelim(']') {
						out.Conflicts = make([]easyjson.RawMessage, 0, 2)
					} else {
						out.Conflicts = []easyjson.RawMessage{}
					}
				} else {
					out.Conflicts = (out.Conflicts)[:0]
				}
				for !in.IsDelim(']') {
					var v6 easyjson.RawMessage
					if in.IsNull() {
						in.Skip()
					} else {
						(v6).UnmarshalEasyJSON(in)
					}
					out.Conflicts = append(out.Conflicts, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel4(out *jwriter.Writer, in SketchDocument) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"workspaceId\":"
		out.RawString(prefix)
		out.String(string(in.WorkspaceID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"createdByUserId\":"
		out.RawString(prefix)
		out.String(string(in.CreatedByUserID))
	}
	{
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	{
		const prefix string = ",\"plane\":"
		out.RawString(prefix)
		(in.Plane).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.Int64(int64(in.Version))
	}
	{
		const prefix string = ",\"entities\":"
		out.RawString(prefix)
		if in.Entities == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v7First := true
			for v7Name, v7Value := range in.Entities {
				if v7First {
					v7First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v7Name))
				out.RawByte(':')
				(v7Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"constraints\":"
		out.RawString(prefix)
		if in.Constraints == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v8First := true
			for v8Name, v8Value := range in.Constraints {
				if v8First {
					v8First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v8Name))
				out.RawByte(':')
				(v8Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"dimensions\":"
		out.RawString(prefix)
		if in.Dimensions == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v9First := true
			for v9Name, v9Value := range in.Dimensions {
				if v9First {
					v9First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v9Name))
				out.RawByte(':')
				(v9Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"groups\":"
		out.RawString(prefix)
		if in.Groups == nil && (out.Flags&jwriter.NilMapAsEmpty) == 0 {
			out.RawString(`null`)
		} else {
			out.RawByte('{')
			v10First := true
			for v10Name, v10Value := range in.Groups {
				if v10First {
					v10First = false
				} else {
					out.RawByte(',')
				}
				out.String(string(v10Name))
				out.RawByte(':')
				(v10Value).MarshalEasyJSON(out)
			}
			out.RawByte('}')
		}
	}
	{
		const prefix string = ",\"solveStatus\":"
		out.RawString(prefix)
		(in.SolveStatus).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"profiles\":"
		out.RawString(prefix)
		if in.Profiles == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Profiles {
				if v11 > 0 {
					out.RawByte(',')
				}
				(v12).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.Conflicts) != 0 {
		const prefix string = ",\"conflicts\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v13, v14 := range in.Conflicts {
				if v13 > 0 {
					out.RawByte(',')
				}
				(v14).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SketchDocument) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SketchDocument) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SketchDocument) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SketchDocument) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel4(l, v)
}
func easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel5(in *jlexer.Lexer, out *CreateSketchRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "unit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Unit = string(in.String())
			}
		case "plane":
			if in.IsNull() {
				in.Skip()
				out.Plane = nil
			} else {
				if out.Plane == nil {
					out.Plane = new(SketchPlane)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Plane).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel5(out *jwriter.Writer, in CreateSketchRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	if in.Unit != "" {
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	{
		const prefix string = ",\"plane\":"
		out.RawString(prefix)
		if in.Plane == nil {
			out.RawString("null")
		} else {
			(*in.Plane).MarshalEasyJSON(out)
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateSketchRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateSketchRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateSketchRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateSketchRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel5(l, v)
}
func easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel6(in *jlexer.Lexer, out *AvailableSketchList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "sketches":
			if in.IsNull() {
				in.Skip()
				out.Sketches = nil
			} else {
				in.Delim('[')
				if out.Sketches == nil {
					if !in.IsDelim(']') {
						out.Sketches = make([]AvailableSketch, 0, 0)
					} else {
						out.Sketches = []AvailableSketch{}
					}
				} else {
					out.Sketches = (out.Sketches)[:0]
				}
				for !in.IsDelim(']') {
					var v15 AvailableSketch
					if in.IsNull() {
						in.Skip()
					} else {
						(v15).UnmarshalEasyJSON(in)
					}
					out.Sketches = append(out.Sketches, v15)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel6(out *jwriter.Writer, in AvailableSketchList) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"sketches\":"
		out.RawString(prefix[1:])
		if in.Sketches == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v16, v17 := range in.Sketches {
				if v16 > 0 {
					out.RawByte(',')
				}
				(v17).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AvailableSketchList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AvailableSketchList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AvailableSketchList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AvailableSketchList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel6(l, v)
}
func easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel7(in *jlexer.Lexer, out *AvailableSketch) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "workspaceId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.WorkspaceID = string(in.String())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		case "createdByUserId":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedByUserID = string(in.String())
			}
		case "unit":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Unit = string(in.String())
			}
		case "plane":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Plane).UnmarshalEasyJSON(in)
			}
		case "version":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Version = int64(in.Int64())
			}
		case "role":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Role = string(in.String())
			}
		case "createdAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.CreatedAt = string(in.String())
			}
		case "updatedAt":
			if in.IsNull() {
				in.Skip()
			} else {
				out.UpdatedAt = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel7(out *jwriter.Writer, in AvailableSketch) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"workspaceId\":"
		out.RawString(prefix)
		out.String(string(in.WorkspaceID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"createdByUserId\":"
		out.RawString(prefix)
		out.String(string(in.CreatedByUserID))
	}
	{
		const prefix string = ",\"unit\":"
		out.RawString(prefix)
		out.String(string(in.Unit))
	}
	{
		const prefix string = ",\"plane\":"
		out.RawString(prefix)
		(in.Plane).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"version\":"
		out.RawString(prefix)
		out.Int64(int64(in.Version))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"createdAt\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	{
		const prefix string = ",\"updatedAt\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AvailableSketch) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AvailableSketch) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson51c6e670EncodeGithubComDnonakolesaxCccadLocksInternalModel7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AvailableSketch) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AvailableSketch) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson51c6e670DecodeGithubComDnonakolesaxCccadLocksInternalModel7(l, v)
}
