// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel(in *jlexer.Lexer, out *SolverDiagnostic) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "level":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Level = string(in.String())
			}
		case "code":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Code = string(in.String())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "entityIds":
			if in.IsNull() {
				in.Skip()
				out.EntityIDs = nil
			} else {
				in.Delim('[')
				if out.EntityIDs == nil {
					if !in.IsDelim(']') {
						out.EntityIDs = make([]string, 0, 4)
					} else {
						out.EntityIDs = []string{}
					}
				} else {
					out.EntityIDs = (out.EntityIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					if in.IsNull() {
						in.Skip()
					} else {
						v1 = string(in.String())
					}
					out.EntityIDs = append(out.EntityIDs, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "constraintIds":
			if in.IsNull() {
				in.Skip()
				out.ConstraintIDs = nil
			} else {
				in.Delim('[')
				if out.ConstraintIDs == nil {
					if !in.IsDelim(']') {
						out.ConstraintIDs = make([]string, 0, 4)
					} else {
						out.ConstraintIDs = []string{}
					}
				} else {
					out.ConstraintIDs = (out.ConstraintIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v2 string
					if in.IsNull() {
						in.Skip()
					} else {
						v2 = string(in.String())
					}
					out.ConstraintIDs = append(out.ConstraintIDs, v2)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "dimensionIds":
			if in.IsNull() {
				in.Skip()
				out.DimensionIDs = nil
			} else {
				in.Delim('[')
				if out.DimensionIDs == nil {
					if !in.IsDelim(']') {
						out.DimensionIDs = make([]string, 0, 4)
					} else {
						out.DimensionIDs = []string{}
					}
				} else {
					out.DimensionIDs = (out.DimensionIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v3 string
					if in.IsNull() {
						in.Skip()
					} else {
						v3 = string(in.String())
					}
					out.DimensionIDs = append(out.DimensionIDs, v3)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel(out *jwriter.Writer, in SolverDiagnostic) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix[1:])
		out.String(string(in.Level))
	}
	{
		const prefix string = ",\"code\":"
		out.RawString(prefix)
		out.String(string(in.Code))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	if len(in.EntityIDs) != 0 {
		const prefix string = ",\"entityIds\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v4, v5 := range in.EntityIDs {
				if v4 > 0 {
					out.RawByte(',')
				}
				out.String(string(v5))
			}
			out.RawByte(']')
		}
	}
	if len(in.ConstraintIDs) != 0 {
		const prefix string = ",\"constraintIds\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v6, v7 := range in.ConstraintIDs {
				if v6 > 0 {
					out.RawByte(',')
				}
				out.String(string(v7))
			}
			out.RawByte(']')
		}
	}
	if len(in.DimensionIDs) != 0 {
		const prefix string = ",\"dimensionIds\":"
		out.RawString(prefix)
		{
			out.RawByte('[')
			for v8, v9 := range in.DimensionIDs {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SolverDiagnostic) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SolverDiagnostic) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SolverDiagnostic) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SolverDiagnostic) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel(l, v)
}
func easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel1(in *jlexer.Lexer, out *SolveStatusInfo) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "degreesOfFreedom":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DegreesOfFreedom = int(in.Int())
			}
		case "message":
			if in.IsNull() {
				in.Skip()
				out.Message = nil
			} else {
				if out.Message == nil {
					out.Message = new(string)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					*out.Message = string(in.String())
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel1(out *jwriter.Writer, in SolveStatusInfo) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	if in.DegreesOfFreedom != 0 {
		const prefix string = ",\"degreesOfFreedom\":"
		out.RawString(prefix)
		out.Int(int(in.DegreesOfFreedom))
	}
	if in.Message != nil {
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(*in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SolveStatusInfo) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SolveStatusInfo) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SolveStatusInfo) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SolveStatusInfo) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel1(l, v)
}
func easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel2(in *jlexer.Lexer, out *SolvePreviewResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Status).UnmarshalEasyJSON(in)
			}
		case "patch":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Patch).UnmarshalEasyJSON(in)
			}
		case "affectedEntityIds":
			if in.IsNull() {
				in.Skip()
				out.AffectedEntityIDs = nil
			} else {
				in.Delim('[')
				if out.AffectedEntityIDs == nil {
					if !in.IsDelim(']') {
						out.AffectedEntityIDs = make([]string, 0, 4)
					} else {
						out.AffectedEntityIDs = []string{}
					}
				} else {
					out.AffectedEntityIDs = (out.AffectedEntityIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v10 string
					if in.IsNull() {
						in.Skip()
					} else {
						v10 = string(in.String())
					}
					out.AffectedEntityIDs = append(out.AffectedEntityIDs, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "diagnostics":
			if in.IsNull() {
				in.Skip()
				out.Diagnostics = nil
			} else {
				in.Delim('[')
				if out.Diagnostics == nil {
					if !in.IsDelim(']') {
						out.Diagnostics = make([]SolverDiagnostic, 0, 0)
					} else {
						out.Diagnostics = []SolverDiagnostic{}
					}
				} else {
					out.Diagnostics = (out.Diagnostics)[:0]
				}
				for !in.IsDelim(']') {
					var v11 SolverDiagnostic
					if in.IsNull() {
						in.Skip()
					} else {
						(v11).UnmarshalEasyJSON(in)
					}
					out.Diagnostics = append(out.Diagnostics, v11)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel2(out *jwriter.Writer, in SolvePreviewResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		(in.Status).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"patch\":"
		out.RawString(prefix)
		(in.Patch).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"affectedEntityIds\":"
		out.RawString(prefix)
		if in.AffectedEntityIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.AffectedEntityIDs {
				if v12 > 0 {
					out.RawByte(',')
				}
				out.String(string(v13))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"diagnostics\":"
		out.RawString(prefix)
		if in.Diagnostics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.Diagnostics {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SolvePreviewResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SolvePreviewResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SolvePreviewResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SolvePreviewResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel2(l, v)
}
func easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel3(in *jlexer.Lexer, out *SolvePreviewRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "baseVersion":
			if in.IsNull() {
				in.Skip()
			} else {
				out.BaseVersion = int64(in.Int64())
			}
		case "intent":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Intent).UnmarshalEasyJSON(in)
			}
		case "options":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Options).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel3(out *jwriter.Writer, in SolvePreviewRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"baseVersion\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.BaseVersion))
	}
	{
		const prefix string = ",\"intent\":"
		out.RawString(prefix)
		(in.Intent).MarshalEasyJSON(out)
	}
	if (in.Options).IsDefined() {
		const prefix string = ",\"options\":"
		out.RawString(prefix)
		(in.Options).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SolvePreviewRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SolvePreviewRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SolvePreviewRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SolvePreviewRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel3(l, v)
}
func easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel4(in *jlexer.Lexer, out *SketchConflict) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "type":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Type = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		case "affectedEntityIds":
			if in.IsNull() {
				in.Skip()
				out.AffectedEntityIDs = nil
			} else {
				in.Delim('[')
				if out.AffectedEntityIDs == nil {
					if !in.IsDelim(']') {
						out.AffectedEntityIDs = make([]string, 0, 4)
					} else {
						out.AffectedEntityIDs = []string{}
					}
				} else {
					out.AffectedEntityIDs = (out.AffectedEntityIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v16 string
					if in.IsNull() {
						in.Skip()
					} else {
						v16 = string(in.String())
					}
					out.AffectedEntityIDs = append(out.AffectedEntityIDs, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "causedByOpIds":
			if in.IsNull() {
				in.Skip()
				out.CausedByOpIDs = nil
			} else {
				in.Delim('[')
				if out.CausedByOpIDs == nil {
					if !in.IsDelim(']') {
						out.CausedByOpIDs = make([]string, 0, 4)
					} else {
						out.CausedByOpIDs = []string{}
					}
				} else {
					out.CausedByOpIDs = (out.CausedByOpIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v17 string
					if in.IsNull() {
						in.Skip()
					} else {
						v17 = string(in.String())
					}
					out.CausedByOpIDs = append(out.CausedByOpIDs, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		case "payload":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Payload).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel4(out *jwriter.Writer, in SketchConflict) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix)
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"affectedEntityIds\":"
		out.RawString(prefix)
		if in.AffectedEntityIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v18, v19 := range in.AffectedEntityIDs {
				if v18 > 0 {
					out.RawByte(',')
				}
				out.String(string(v19))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"causedByOpIds\":"
		out.RawString(prefix)
		if in.CausedByOpIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.CausedByOpIDs {
				if v20 > 0 {
					out.RawByte(',')
				}
				out.String(string(v21))
			}
			out.RawByte(']')
		}
	}
	if in.Message != "" {
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	if (in.Payload).IsDefined() {
		const prefix string = ",\"payload\":"
		out.RawString(prefix)
		(in.Payload).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SketchConflict) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SketchConflict) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SketchConflict) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SketchConflict) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel4(l, v)
}
func easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel5(in *jlexer.Lexer, out *ConstraintComponent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "id":
			if in.IsNull() {
				in.Skip()
			} else {
				out.ID = string(in.String())
			}
		case "entityIds":
			if in.IsNull() {
				in.Skip()
				out.EntityIDs = nil
			} else {
				in.Delim('[')
				if out.EntityIDs == nil {
					if !in.IsDelim(']') {
						out.EntityIDs = make([]string, 0, 4)
					} else {
						out.EntityIDs = []string{}
					}
				} else {
					out.EntityIDs = (out.EntityIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v22 string
					if in.IsNull() {
						in.Skip()
					} else {
						v22 = string(in.String())
					}
					out.EntityIDs = append(out.EntityIDs, v22)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "constraintIds":
			if in.IsNull() {
				in.Skip()
				out.ConstraintIDs = nil
			} else {
				in.Delim('[')
				if out.ConstraintIDs == nil {
					if !in.IsDelim(']') {
						out.ConstraintIDs = make([]string, 0, 4)
					} else {
						out.ConstraintIDs = []string{}
					}
				} else {
					out.ConstraintIDs = (out.ConstraintIDs)[:0]
				}
				for !in.IsDelim(']') {
					var v23 string
					if in.IsNull() {
						in.Skip()
					} else {
						v23 = string(in.String())
					}
					out.ConstraintIDs = append(out.ConstraintIDs, v23)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "degreesOfFreedom":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DegreesOfFreedom = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel5(out *jwriter.Writer, in ConstraintComponent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"entityIds\":"
		out.RawString(prefix)
		if in.EntityIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v24, v25 := range in.EntityIDs {
				if v24 > 0 {
					out.RawByte(',')
				}
				out.String(string(v25))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"constraintIds\":"
		out.RawString(prefix)
		if in.ConstraintIDs == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v26, v27 := range in.ConstraintIDs {
				if v26 > 0 {
					out.RawByte(',')
				}
				out.String(string(v27))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"degreesOfFreedom\":"
		out.RawString(prefix)
		out.Int(int(in.DegreesOfFreedom))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ConstraintComponent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ConstraintComponent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ConstraintComponent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ConstraintComponent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel5(l, v)
}
func easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel6(in *jlexer.Lexer, out *AnalyzeSketchResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				(out.Status).UnmarshalEasyJSON(in)
			}
		case "degreesOfFreedom":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DegreesOfFreedom = int(in.Int())
			}
		case "components":
			if in.IsNull() {
				in.Skip()
				out.Components = nil
			} else {
				in.Delim('[')
				if out.Components == nil {
					if !in.IsDelim(']') {
						out.Components = make([]ConstraintComponent, 0, 0)
					} else {
						out.Components = []ConstraintComponent{}
					}
				} else {
					out.Components = (out.Components)[:0]
				}
				for !in.IsDelim(']') {
					var v28 ConstraintComponent
					if in.IsNull() {
						in.Skip()
					} else {
						(v28).UnmarshalEasyJSON(in)
					}
					out.Components = append(out.Components, v28)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "diagnostics":
			if in.IsNull() {
				in.Skip()
				out.Diagnostics = nil
			} else {
				in.Delim('[')
				if out.Diagnostics == nil {
					if !in.IsDelim(']') {
						out.Diagnostics = make([]SolverDiagnostic, 0, 0)
					} else {
						out.Diagnostics = []SolverDiagnostic{}
					}
				} else {
					out.Diagnostics = (out.Diagnostics)[:0]
				}
				for !in.IsDelim(']') {
					var v29 SolverDiagnostic
					if in.IsNull() {
						in.Skip()
					} else {
						(v29).UnmarshalEasyJSON(in)
					}
					out.Diagnostics = append(out.Diagnostics, v29)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel6(out *jwriter.Writer, in AnalyzeSketchResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		(in.Status).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"degreesOfFreedom\":"
		out.RawString(prefix)
		out.Int(int(in.DegreesOfFreedom))
	}
	{
		const prefix string = ",\"components\":"
		out.RawString(prefix)
		if in.Components == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v30, v31 := range in.Components {
				if v30 > 0 {
					out.RawByte(',')
				}
				(v31).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"diagnostics\":"
		out.RawString(prefix)
		if in.Diagnostics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v32, v33 := range in.Diagnostics {
				if v32 > 0 {
					out.RawByte(',')
				}
				(v33).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AnalyzeSketchResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AnalyzeSketchResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson3c49fc01EncodeGithubComDnonakolesaxCccadLocksInternalModel6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AnalyzeSketchResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AnalyzeSketchResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson3c49fc01DecodeGithubComDnonakolesaxCccadLocksInternalModel6(l, v)
}
