// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/solver/v1/sketch_solver.proto

package solverv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SketchSolver_Solve_FullMethodName       = "/cccad.solver.v1.SketchSolver/Solve"
	SketchSolver_Check_FullMethodName       = "/cccad.solver.v1.SketchSolver/Check"
	SketchSolver_ApplyIntent_FullMethodName = "/cccad.solver.v1.SketchSolver/ApplyIntent"
	SketchSolver_Analyze_FullMethodName     = "/cccad.solver.v1.SketchSolver/Analyze"
)

// SketchSolverClient is the client API for SketchSolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SketchSolver is a pure computational service.
// It must not know anything about users, workspaces, Keycloak, permissions,
// WebSocket sessions or database transactions.
type SketchSolverClient interface {
	// Solves the full sketch model and returns materialized geometry.
	Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error)
	// Checks constraint system validity and returns diagnostics without applying user intent.
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	// Applies a solver-level user intent, such as dragging a point or changing a driving dimension.
	ApplyIntent(ctx context.Context, in *ApplyIntentRequest, opts ...grpc.CallOption) (*ApplyIntentResponse, error)
	// Analyzes constraint components, degrees of freedom and problematic regions.
	Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type sketchSolverClient struct {
	cc grpc.ClientConnInterface
}

func NewSketchSolverClient(cc grpc.ClientConnInterface) SketchSolverClient {
	return &sketchSolverClient{cc}
}

func (c *sketchSolverClient) Solve(ctx context.Context, in *SolveRequest, opts ...grpc.CallOption) (*SolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SolveResponse)
	err := c.cc.Invoke(ctx, SketchSolver_Solve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketchSolverClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, SketchSolver_Check_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketchSolverClient) ApplyIntent(ctx context.Context, in *ApplyIntentRequest, opts ...grpc.CallOption) (*ApplyIntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyIntentResponse)
	err := c.cc.Invoke(ctx, SketchSolver_ApplyIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sketchSolverClient) Analyze(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, SketchSolver_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SketchSolverServer is the server API for SketchSolver service.
// All implementations must embed UnimplementedSketchSolverServer
// for forward compatibility.
//
// SketchSolver is a pure computational service.
// It must not know anything about users, workspaces, Keycloak, permissions,
// WebSocket sessions or database transactions.
type SketchSolverServer interface {
	// Solves the full sketch model and returns materialized geometry.
	Solve(context.Context, *SolveRequest) (*SolveResponse, error)
	// Checks constraint system validity and returns diagnostics without applying user intent.
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	// Applies a solver-level user intent, such as dragging a point or changing a driving dimension.
	ApplyIntent(context.Context, *ApplyIntentRequest) (*ApplyIntentResponse, error)
	// Analyzes constraint components, degrees of freedom and problematic regions.
	Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedSketchSolverServer()
}

// UnimplementedSketchSolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSketchSolverServer struct{}

func (UnimplementedSketchSolverServer) Solve(context.Context, *SolveRequest) (*SolveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedSketchSolverServer) Check(context.Context, *CheckRequest) (*CheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Check not implemented")
}
func (UnimplementedSketchSolverServer) ApplyIntent(context.Context, *ApplyIntentRequest) (*ApplyIntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyIntent not implemented")
}
func (UnimplementedSketchSolverServer) Analyze(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedSketchSolverServer) mustEmbedUnimplementedSketchSolverServer() {}
func (UnimplementedSketchSolverServer) testEmbeddedByValue()                      {}

// UnsafeSketchSolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SketchSolverServer will
// result in compilation errors.
type UnsafeSketchSolverServer interface {
	mustEmbedUnimplementedSketchSolverServer()
}

func RegisterSketchSolverServer(s grpc.ServiceRegistrar, srv SketchSolverServer) {
	// If the following call panics, it indicates UnimplementedSketchSolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SketchSolver_ServiceDesc, srv)
}

func _SketchSolver_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchSolverServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchSolver_Solve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchSolverServer).Solve(ctx, req.(*SolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SketchSolver_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchSolverServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchSolver_Check_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchSolverServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SketchSolver_ApplyIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyIntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchSolverServer).ApplyIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchSolver_ApplyIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchSolverServer).ApplyIntent(ctx, req.(*ApplyIntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SketchSolver_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SketchSolverServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SketchSolver_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SketchSolverServer).Analyze(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SketchSolver_ServiceDesc is the grpc.ServiceDesc for SketchSolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SketchSolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cccad.solver.v1.SketchSolver",
	HandlerType: (*SketchSolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _SketchSolver_Solve_Handler,
		},
		{
			MethodName: "Check",
			Handler:    _SketchSolver_Check_Handler,
		},
		{
			MethodName: "ApplyIntent",
			Handler:    _SketchSolver_ApplyIntent_Handler,
		},
		{
			MethodName: "Analyze",
			Handler:    _SketchSolver_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/solver/v1/sketch_solver.proto",
}
