// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/3d/v1/geometry_kernel.proto

package geometryv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GeometrySolverService_Health_FullMethodName       = "/cccad.geometry.v1.GeometrySolverService/Health"
	GeometrySolverService_BuildExtrude_FullMethodName = "/cccad.geometry.v1.GeometrySolverService/BuildExtrude"
	GeometrySolverService_BuildHole_FullMethodName    = "/cccad.geometry.v1.GeometrySolverService/BuildHole"
	GeometrySolverService_BuildFillet_FullMethodName  = "/cccad.geometry.v1.GeometrySolverService/BuildFillet"
	GeometrySolverService_BuildChamfer_FullMethodName = "/cccad.geometry.v1.GeometrySolverService/BuildChamfer"
	GeometrySolverService_BuildPattern_FullMethodName = "/cccad.geometry.v1.GeometrySolverService/BuildPattern"
	GeometrySolverService_BuildBoolean_FullMethodName = "/cccad.geometry.v1.GeometrySolverService/BuildBoolean"
	GeometrySolverService_RebuildPart_FullMethodName  = "/cccad.geometry.v1.GeometrySolverService/RebuildPart"
	GeometrySolverService_GetTopology_FullMethodName  = "/cccad.geometry.v1.GeometrySolverService/GetTopology"
	GeometrySolverService_GetFacePlane_FullMethodName = "/cccad.geometry.v1.GeometrySolverService/GetFacePlane"
)

// GeometrySolverServiceClient is the client API for GeometrySolverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Internal C++ geometry solver contract.
// Source of truth remains in the Go backend: sketches, features, versions and permissions.
// This service receives normalized 3D feature input and returns BREP/preview artifacts,
// topology metadata and structured diagnostics.
type GeometrySolverServiceClient interface {
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Build a single feature in isolation. Useful for preview, validation and MVP flow.
	BuildExtrude(ctx context.Context, in *BuildExtrudeRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error)
	BuildHole(ctx context.Context, in *BuildHoleRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error)
	BuildFillet(ctx context.Context, in *BuildFilletRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error)
	BuildChamfer(ctx context.Context, in *BuildChamferRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error)
	BuildPattern(ctx context.Context, in *BuildPatternRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error)
	BuildBoolean(ctx context.Context, in *BuildBooleanRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error)
	// Canonical operation: rebuild an ordered feature history for a part.
	RebuildPart(ctx context.Context, in *RebuildPartRequest, opts ...grpc.CallOption) (*RebuildPartResponse, error)
	// Topology queries used by frontend face/edge picking and sketch-on-face.
	GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error)
	GetFacePlane(ctx context.Context, in *GetFacePlaneRequest, opts ...grpc.CallOption) (*GetFacePlaneResponse, error)
}

type geometrySolverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeometrySolverServiceClient(cc grpc.ClientConnInterface) GeometrySolverServiceClient {
	return &geometrySolverServiceClient{cc}
}

func (c *geometrySolverServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometrySolverServiceClient) BuildExtrude(ctx context.Context, in *BuildExtrudeRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildFeatureResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_BuildExtrude_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometrySolverServiceClient) BuildHole(ctx context.Context, in *BuildHoleRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildFeatureResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_BuildHole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometrySolverServiceClient) BuildFillet(ctx context.Context, in *BuildFilletRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildFeatureResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_BuildFillet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometrySolverServiceClient) BuildChamfer(ctx context.Context, in *BuildChamferRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildFeatureResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_BuildChamfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometrySolverServiceClient) BuildPattern(ctx context.Context, in *BuildPatternRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildFeatureResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_BuildPattern_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometrySolverServiceClient) BuildBoolean(ctx context.Context, in *BuildBooleanRequest, opts ...grpc.CallOption) (*BuildFeatureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuildFeatureResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_BuildBoolean_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometrySolverServiceClient) RebuildPart(ctx context.Context, in *RebuildPartRequest, opts ...grpc.CallOption) (*RebuildPartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RebuildPartResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_RebuildPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometrySolverServiceClient) GetTopology(ctx context.Context, in *GetTopologyRequest, opts ...grpc.CallOption) (*GetTopologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopologyResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_GetTopology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *geometrySolverServiceClient) GetFacePlane(ctx context.Context, in *GetFacePlaneRequest, opts ...grpc.CallOption) (*GetFacePlaneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFacePlaneResponse)
	err := c.cc.Invoke(ctx, GeometrySolverService_GetFacePlane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeometrySolverServiceServer is the server API for GeometrySolverService service.
// All implementations must embed UnimplementedGeometrySolverServiceServer
// for forward compatibility.
//
// Internal C++ geometry solver contract.
// Source of truth remains in the Go backend: sketches, features, versions and permissions.
// This service receives normalized 3D feature input and returns BREP/preview artifacts,
// topology metadata and structured diagnostics.
type GeometrySolverServiceServer interface {
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Build a single feature in isolation. Useful for preview, validation and MVP flow.
	BuildExtrude(context.Context, *BuildExtrudeRequest) (*BuildFeatureResponse, error)
	BuildHole(context.Context, *BuildHoleRequest) (*BuildFeatureResponse, error)
	BuildFillet(context.Context, *BuildFilletRequest) (*BuildFeatureResponse, error)
	BuildChamfer(context.Context, *BuildChamferRequest) (*BuildFeatureResponse, error)
	BuildPattern(context.Context, *BuildPatternRequest) (*BuildFeatureResponse, error)
	BuildBoolean(context.Context, *BuildBooleanRequest) (*BuildFeatureResponse, error)
	// Canonical operation: rebuild an ordered feature history for a part.
	RebuildPart(context.Context, *RebuildPartRequest) (*RebuildPartResponse, error)
	// Topology queries used by frontend face/edge picking and sketch-on-face.
	GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error)
	GetFacePlane(context.Context, *GetFacePlaneRequest) (*GetFacePlaneResponse, error)
	mustEmbedUnimplementedGeometrySolverServiceServer()
}

// UnimplementedGeometrySolverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeometrySolverServiceServer struct{}

func (UnimplementedGeometrySolverServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedGeometrySolverServiceServer) BuildExtrude(context.Context, *BuildExtrudeRequest) (*BuildFeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildExtrude not implemented")
}
func (UnimplementedGeometrySolverServiceServer) BuildHole(context.Context, *BuildHoleRequest) (*BuildFeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildHole not implemented")
}
func (UnimplementedGeometrySolverServiceServer) BuildFillet(context.Context, *BuildFilletRequest) (*BuildFeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildFillet not implemented")
}
func (UnimplementedGeometrySolverServiceServer) BuildChamfer(context.Context, *BuildChamferRequest) (*BuildFeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildChamfer not implemented")
}
func (UnimplementedGeometrySolverServiceServer) BuildPattern(context.Context, *BuildPatternRequest) (*BuildFeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildPattern not implemented")
}
func (UnimplementedGeometrySolverServiceServer) BuildBoolean(context.Context, *BuildBooleanRequest) (*BuildFeatureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BuildBoolean not implemented")
}
func (UnimplementedGeometrySolverServiceServer) RebuildPart(context.Context, *RebuildPartRequest) (*RebuildPartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RebuildPart not implemented")
}
func (UnimplementedGeometrySolverServiceServer) GetTopology(context.Context, *GetTopologyRequest) (*GetTopologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopology not implemented")
}
func (UnimplementedGeometrySolverServiceServer) GetFacePlane(context.Context, *GetFacePlaneRequest) (*GetFacePlaneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFacePlane not implemented")
}
func (UnimplementedGeometrySolverServiceServer) mustEmbedUnimplementedGeometrySolverServiceServer() {}
func (UnimplementedGeometrySolverServiceServer) testEmbeddedByValue()                               {}

// UnsafeGeometrySolverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeometrySolverServiceServer will
// result in compilation errors.
type UnsafeGeometrySolverServiceServer interface {
	mustEmbedUnimplementedGeometrySolverServiceServer()
}

func RegisterGeometrySolverServiceServer(s grpc.ServiceRegistrar, srv GeometrySolverServiceServer) {
	// If the following call panics, it indicates UnimplementedGeometrySolverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GeometrySolverService_ServiceDesc, srv)
}

func _GeometrySolverService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometrySolverService_BuildExtrude_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildExtrudeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).BuildExtrude(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_BuildExtrude_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).BuildExtrude(ctx, req.(*BuildExtrudeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometrySolverService_BuildHole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildHoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).BuildHole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_BuildHole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).BuildHole(ctx, req.(*BuildHoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometrySolverService_BuildFillet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildFilletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).BuildFillet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_BuildFillet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).BuildFillet(ctx, req.(*BuildFilletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometrySolverService_BuildChamfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildChamferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).BuildChamfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_BuildChamfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).BuildChamfer(ctx, req.(*BuildChamferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometrySolverService_BuildPattern_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildPatternRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).BuildPattern(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_BuildPattern_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).BuildPattern(ctx, req.(*BuildPatternRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometrySolverService_BuildBoolean_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildBooleanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).BuildBoolean(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_BuildBoolean_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).BuildBoolean(ctx, req.(*BuildBooleanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometrySolverService_RebuildPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).RebuildPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_RebuildPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).RebuildPart(ctx, req.(*RebuildPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometrySolverService_GetTopology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).GetTopology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_GetTopology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).GetTopology(ctx, req.(*GetTopologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeometrySolverService_GetFacePlane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFacePlaneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeometrySolverServiceServer).GetFacePlane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GeometrySolverService_GetFacePlane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeometrySolverServiceServer).GetFacePlane(ctx, req.(*GetFacePlaneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeometrySolverService_ServiceDesc is the grpc.ServiceDesc for GeometrySolverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeometrySolverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cccad.geometry.v1.GeometrySolverService",
	HandlerType: (*GeometrySolverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _GeometrySolverService_Health_Handler,
		},
		{
			MethodName: "BuildExtrude",
			Handler:    _GeometrySolverService_BuildExtrude_Handler,
		},
		{
			MethodName: "BuildHole",
			Handler:    _GeometrySolverService_BuildHole_Handler,
		},
		{
			MethodName: "BuildFillet",
			Handler:    _GeometrySolverService_BuildFillet_Handler,
		},
		{
			MethodName: "BuildChamfer",
			Handler:    _GeometrySolverService_BuildChamfer_Handler,
		},
		{
			MethodName: "BuildPattern",
			Handler:    _GeometrySolverService_BuildPattern_Handler,
		},
		{
			MethodName: "BuildBoolean",
			Handler:    _GeometrySolverService_BuildBoolean_Handler,
		},
		{
			MethodName: "RebuildPart",
			Handler:    _GeometrySolverService_RebuildPart_Handler,
		},
		{
			MethodName: "GetTopology",
			Handler:    _GeometrySolverService_GetTopology_Handler,
		},
		{
			MethodName: "GetFacePlane",
			Handler:    _GeometrySolverService_GetFacePlane_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/3d/v1/geometry_kernel.proto",
}
