// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: internal/proto/auth/v1/auth.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserTokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          string                 `protobuf:"bytes,1,opt,name=Auth,proto3" json:"Auth,omitempty"`
	Refresh       string                 `protobuf:"bytes,2,opt,name=Refresh,proto3" json:"Refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTokens) Reset() {
	*x = UserTokens{}
	mi := &file_internal_proto_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTokens) ProtoMessage() {}

func (x *UserTokens) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTokens.ProtoReflect.Descriptor instead.
func (*UserTokens) Descriptor() ([]byte, []int) {
	return file_internal_proto_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserTokens) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *UserTokens) GetRefresh() string {
	if x != nil {
		return x.Refresh
	}
	return ""
}

type TokenData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	At            *string                `protobuf:"bytes,2,opt,name=at,proto3,oneof" json:"at,omitempty"`
	Rt            *string                `protobuf:"bytes,3,opt,name=rt,proto3,oneof" json:"rt,omitempty"`
	It            *string                `protobuf:"bytes,4,opt,name=it,proto3,oneof" json:"it,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenData) Reset() {
	*x = TokenData{}
	mi := &file_internal_proto_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenData) ProtoMessage() {}

func (x *TokenData) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenData.ProtoReflect.Descriptor instead.
func (*TokenData) Descriptor() ([]byte, []int) {
	return file_internal_proto_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *TokenData) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *TokenData) GetAt() string {
	if x != nil && x.At != nil {
		return *x.At
	}
	return ""
}

func (x *TokenData) GetRt() string {
	if x != nil && x.Rt != nil {
		return *x.Rt
	}
	return ""
}

func (x *TokenData) GetIt() string {
	if x != nil && x.It != nil {
		return *x.It
	}
	return ""
}

var File_internal_proto_auth_v1_auth_proto protoreflect.FileDescriptor

const file_internal_proto_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/auth/v1/auth.proto\x12\x04auth\":\n" +
	"\n" +
	"UserTokens\x12\x12\n" +
	"\x04Auth\x18\x01 \x01(\tR\x04Auth\x12\x18\n" +
	"\aRefresh\x18\x02 \x01(\tR\aRefresh\"o\n" +
	"\tTokenData\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x13\n" +
	"\x02at\x18\x02 \x01(\tH\x00R\x02at\x88\x01\x01\x12\x13\n" +
	"\x02rt\x18\x03 \x01(\tH\x01R\x02rt\x88\x01\x01\x12\x13\n" +
	"\x02it\x18\x04 \x01(\tH\x02R\x02it\x88\x01\x01B\x05\n" +
	"\x03_atB\x05\n" +
	"\x03_rtB\x05\n" +
	"\x03_it2C\n" +
	"\vAuthService\x124\n" +
	"\rAuthUserIDCtx\x12\x10.auth.UserTokens\x1a\x0f.auth.TokenData\"\x00BCZAgithub.com/dnonakolesax/cccad-locks/internal/proto/auth/v1;authv1b\x06proto3"

var (
	file_internal_proto_auth_v1_auth_proto_rawDescOnce sync.Once
	file_internal_proto_auth_v1_auth_proto_rawDescData []byte
)

func file_internal_proto_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_internal_proto_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_internal_proto_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_auth_v1_auth_proto_rawDesc), len(file_internal_proto_auth_v1_auth_proto_rawDesc)))
	})
	return file_internal_proto_auth_v1_auth_proto_rawDescData
}

var file_internal_proto_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_proto_auth_v1_auth_proto_goTypes = []any{
	(*UserTokens)(nil), // 0: auth.UserTokens
	(*TokenData)(nil),  // 1: auth.TokenData
}
var file_internal_proto_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.AuthService.AuthUserIDCtx:input_type -> auth.UserTokens
	1, // 1: auth.AuthService.AuthUserIDCtx:output_type -> auth.TokenData
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_auth_v1_auth_proto_init() }
func file_internal_proto_auth_v1_auth_proto_init() {
	if File_internal_proto_auth_v1_auth_proto != nil {
		return
	}
	file_internal_proto_auth_v1_auth_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_auth_v1_auth_proto_rawDesc), len(file_internal_proto_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_internal_proto_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_internal_proto_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_internal_proto_auth_v1_auth_proto = out.File
	file_internal_proto_auth_v1_auth_proto_goTypes = nil
	file_internal_proto_auth_v1_auth_proto_depIdxs = nil
}
